version: '3.5'

services:
  dwh-mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD: BrownOrchid123
      ACCEPT_EULA: "Y" # Add Persistence
      MSSQL_TCP_PORT: 1433
    ports:
      - 1433:1433

  # app-mssql:
  #   image: mcr.microsoft.com/mssql/server
  #   restart: always
  #   environment:
  #     SA_PASSWORD: BrownOrchid123
  #     ACCEPT_EULA: "Y" # Add Persistence
  #     MSSQL_TCP_PORT: 1433
  #   ports:
  #     - 1434:1433
